# Generated by Django 4.2.25 on 2025-11-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
