# Generated by Django 4.2.25 on 2025-11-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram manzili (ixtiyoriy)'),
        ),
    ]
