# Generated by Django 4.2.25 on 2025-11-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_artwork_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name="Asar o'lchami"),
        ),
    ]
